language: python
python:
  - "3.6"
before_install:
  - pip install --upgrade pip
# command to install dependencies
install: "pip install ."
before_script: "python -m spacy download en --user"
# command to run tests
script: pytest
